services:
  producer:
    build: ./producer
    environment:
      - QUEUE_HOST=queue
      - QUEUE_NAME=test_queue
    depends_on:
      queue:
        condition: service_healthy

  consumer:
    build: ./consumer
    environment:
      - QUEUE_HOST=queue
      - QUEUE_NAME=test_queue
      - PYTHONUNBUFFERED=1
    depends_on:
      queue:
        condition: service_healthy

  queue:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5672:5672"
    expose:
      - "5672"
